name: get proxy

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v4  # Mettre à jour vers la version 4

      - name: Setup python
        uses: actions/setup-python@v3  # Aucune mise à jour nécessaire, déjà à la version 3

      - name: Install python packages
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Pull files
        run: |
          git config --local user.email "breakingtechfr@gmail.com"
          git config --local user.name "BreakingTechFR"
          git pull origin main

      - name: Get proxies
        run: python getproxy.py

      - name: Commit files
        run: |
          git add .
          git add -u :/
          git commit -m "Update Proxies (`date '+%F %H:%M %Z'`)"
          git branch -u origin/main

      - name: Push changes
        uses: ad-m/github-push-action@v0.7.0
        with:
          github_token: ${{ secrets.TOKEN_GITHUB }}
          branch: main
